### ISSUE TITLE
Some RSS readers show new undated items everyday in their "Today" view

### ISSUE THREAD

**Issue by knowler** [j9t/frontenddogma.com-forum#1]
I use NetNewsWire on my phone. For the past couple of days, there's been all of the UITest tools in my "Today" view. I think it's because none of these feed items have dates associated with them.

Also, from doing a cursory look over the RSS feed file, it reminded me of another behaviour of this feed in my reader. If I don't check the reader for a few days any new items will always be included in the "Today" view. I think this might be because the "pubDate" isn't a sufficient date marker for the reader to know when the feed item was actually added.

**Comment by j9t** [comment]
Hi @knowler—thanks for reaching out, and sorry about the hiccups!

I’d say “hiccup” at this point because with the merger with UITest.com, tools had to be folded into the main feed, which resulted in many new entries. Fine-tuning feed fields and the number of entries had “not helped,” then, prompting me to also [warn about some inconvenience](https://mas.to/@frontenddogma/109556192482661214).

Now just this noon (CET) I rolled out the latest (and hopefully last) major update. While tool entries still don’t have a date (I keep a longer story short), the _order_ and overall pool of entries should now be set.

Would you be available to monitor this for a few days? While I may need to draw a line somewhere when something looks like a feed reader issue, I’ll want to do what I can on my side. Thank you!

**Comment by j9t** [comment]
Hi @knowler—I had made some more adjustments last month; did things improve since, how was your experience as of late?

**Comment by knowler** [comment]
@j9t Sorry, I never got back to you. Seems a lot better lately. I check RSS pretty much daily, so that might be why. I did just load up a feed reader that I don’t use regularly (Newsboat) and I can see all the new items since I last open it showing up for “January 19.” Not sure if there are any ways to improve that, but I don’t think it’s too much of an issue.

**Comment by j9t** [comment]
Good to hear it’s better!

Do you mean that all the new items are said to have been published on Jan 19? The feed items don’t come with a “pubDate” at the moment, so this specific feed reader may just show unread items for the current day (there are other feed readers which handle this more elegantly, keeping track of when they first register a new item). I might be able to change this adding dates back for news, but that’s just half a solution (tools don’t get dates on FD), and so far it _seems_ it largely works.

Happy about a second opinion and to learn about cases where there are problems—thanks again for bringing this up!

**Comment by j9t** [comment]
@knowler, although tools are still “undated,” these are in the minority and things should have improved. I.e., at the moment I cannot spot and am not aware of any issues.

I’d close this for now, but feel free to reopen if there are continued problems. (Any detail appreciated.)

**Comment by justinferrell** [comment]
Hi! 

I'm running into an issue when trying to subscribe to FD in [Tapestry](http://usetapestry.com) because it requires dates for entries.  Even when I subscribe via NetNewsWire, it just assigns all posts to "right now" so they don't sort properly in the timeline.

I'm subscribing via the RSS feed of the Mastodon account right now but I'd love to subscribe to the website proper. 

This is the feed I'm trying, for reference: https://frontenddogma.com/feed/

Love the content!

**Comment by j9t** [comment]
Thanks @justinferrell—also for taking the time to look for an existing report around this!

Based on what I know, I’m leaning towards not currently investing in this:

1. I’m not aware of more such issues, and that includes knowing that other feed readers, like Feedly, handle the FD feeds fine. From that view, this can be considered a feed reader issue.

2. It’s more complicated to fix, because FD dates are based on publication dates of the original entries (as that makes for value of the entire chronological sorting on the site), not the dates of when these entries were published on FD (which I don’t store, and for which Git or “last modified” dates are not reliable). On any other site, these dates would coincide, but here they don’t.

I’ll monitor this and am happy to take suggestions, yet this makes it hard to take action. I do believe that reporting this to the respective feed reader has merit though—handling dateless entries works in other feed readers (after all, it’s an optional field), and supporting this should improve the feed reader itself.

**Comment by justinferrell** [comment]
Thanks, @j9t!

**Comment by j9t** [comment]
Thanks, too, @justinferrell, and sorry this isn’t more helpful!

**Comment by justinferrell** [comment]
No sweat! I apprecate you even checking it out so quickly. Have a good weekend!
